steps:
    - id: "Push imagem"
      name: "gcr.io/cloud-builders/docker"
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafio-ci:latest', '.']

    - id: go_test
      name: "gcr.io/cloud-builders/go"
      env: ["GOPATH=."]
      args: ['test', 'soma']

    - id: your_step_here
      name: "gcr.io/cloud-builders/go"
      args: ["run","soma"]
      env: ["GOPATH=."]

images:
    - 'gcr.io/$PROJECT_ID/desafio-ci:latest'

tags: ['cloud-builders-community']

