steps:
    - id: "Push imagem"
      name: "gcr.io/cloud-builders/docker"
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafio-ci', '.']

    #  - id: go_version
    #    name: "gcr.io/cloud-builders/go"
    #    args: ["version"]
    #    env: ["GOPATH=."]

    #  - id: go_linter
    #    name: "golangci/golangci-lint"
    #    args: ["golangci-lint","run"]

    - id: go_test
      name: "gcr.io/cloud-builders/go"
      env: ["GOPATH=."]
      args: ["test", "."]

    #- id: your_step_here
    #name: "gcr.io/cloud-builders/go"
    #args: ["run","soma"]
    #env: ["GOPATH=./src"]

images:
    - 'gcr.io/$PROJECT_ID/desafio-ci:latest'

