steps:
  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=."]

  - id: go_linter
    name: "golangci/golangci-lint"
    args: ["golangci-lint","run"]

  - id: go_test
    name: "gcr.io/cloud-builders/go"
    args: ["test","soma"]
    env: ["GOPATH=."]

  - id: go_security
    name: "securego/gosec"
    args: ["soma"]
    env: ["GOPATH=."]

  - id: your_step_here
    name: "gcr.io/cloud-builders/go"
    args: ["run","soma"]
    env: ["GOPATH=."]
