steps:
    - id: "Push imagem"
      name: "gcr.io/cloud-builders/docker"
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafio-ci', '.']

    - id: go_test
      name: "gcr.io/cloud-builders/go"
      env: ["GOPATH=go"]
      args: ['test', '-v', 'soma']

    - id: your_step_here
      name: "gcr.io/cloud-builders/go"
      args: ["run","soma"]
      env: ["GOPATH=go"]

images:
    - 'gcr.io/$PROJECT_ID/desafio-ci'

